# see also https://github.com/whitequark/parser/blob/master/.github/workflows/test.yml
name: Rake

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ["3.0", "3.3"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Bundle install
        run: |
          bundle config path /home/runner/bundle
          bundle install
          bundle update
      - name: Run the default task
        run: bundle exec rake
